"""Initial migration

Revision ID: 478408f49e5c
Revises: e8522182e452
Create Date: 2025-12-01 11:12:06.849726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '478408f49e5c'
down_revision = 'e8522182e452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Applicant',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Employer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('salary_min', sa.Float(precision=50), nullable=True),
    sa.Column('salary_max', sa.Float(precision=50), nullable=True),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_of_applicants', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('JobApplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('resume_path', sa.String(length=255), nullable=True),
    sa.Column('cover_letter_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['Applicant.user_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['Job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employer')
    op.drop_table('applicant')
    op.drop_table('jobapplication')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('user')
    op.drop_table('job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('requirements', mysql.TEXT(), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('salary_min', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('salary_max', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('date_posted', mysql.DATETIME(), nullable=True),
    sa.Column('date_updated', mysql.DATETIME(), nullable=True),
    sa.Column('no_of_applicants', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['user.user_id'], name='job_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('user_type', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('jobapplication',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('applicant_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('application_date', mysql.DATETIME(), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('resume_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cover_letter_path', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=150), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.user_id'], name=op.f('jobapplication_ibfk_1')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('jobapplication_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('applicant',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('applicant_ibfk_1')),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('employer',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('employer_ibfk_1')),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('JobApplication')
    op.drop_table('Job')
    op.drop_table('Employer')
    op.drop_table('Applicant')
    op.drop_table('User')
    # ### end Alembic commands ###
