"""fixed enum data types

Revision ID: 6357bb6f8278
Revises: 
Create Date: 2025-12-03 18:37:52.881438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6357bb6f8278'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('JobCategory',
    sa.Column('jobcat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('jobcat_id')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('verification_doc', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('user_type', sa.Enum('A', 'E', name='usertype'), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Varified', 'Rejected', name='userstatus'), nullable=False),
    sa.Column('date_registered', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Applicant',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('skills', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Employer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_title', sa.String(length=50), nullable=False),
    sa.Column('business_description', sa.String(length=255), nullable=False),
    sa.Column('position_title', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('business_title')
    )
    op.create_table('Notification',
    sa.Column('notif_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('date_sent', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('notif_id')
    )
    op.create_table('Job',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('salary_range', sa.String(length=50), nullable=False),
    sa.Column('employment_type', sa.String(length=25), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Closed', name='jobstatus'), nullable=False),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_of_applicants', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['JobCategory.jobcat_id'], ),
    sa.ForeignKeyConstraint(['employer_id'], ['Employer.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('JobApplication',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Accepted', 'Rejected', 'Withdrawn', name='jobapplicationstatus'), nullable=False),
    sa.Column('resume_file', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['Applicant.user_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['Job.job_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('JobApplication')
    op.drop_table('Job')
    op.drop_table('Notification')
    op.drop_table('Employer')
    op.drop_table('Applicant')
    op.drop_table('User')
    op.drop_table('JobCategory')
    op.drop_table('Admin')
    # ### end Alembic commands ###
