"""Initial migration

Revision ID: e8522182e452
Revises: 
Create Date: 2025-10-11 11:10:34.901641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8522182e452'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Applicant',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Employer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('salary_min', sa.Float(precision=50), nullable=True),
    sa.Column('salary_max', sa.Float(precision=50), nullable=True),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_of_applicants', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('JobApplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('resume_path', sa.String(length=255), nullable=True),
    sa.Column('cover_letter_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['Applicant.user_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['Job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('JobApplication')
    op.drop_table('Job')
    op.drop_table('Employer')
    op.drop_table('Applicant')
    op.drop_table('User')
    # ### end Alembic commands ###
